### ISSUE TITLE
doesn't install when non-root

### ISSUE THREAD

**Issue by yuriiz** [monkeython/loremipsum#1]
Steps to reproduce:

> pip install --user https://github.com/monkeython/loremipsum/zipball/master

Expected:

Should install into ~/.local

Actual:

```
  File "build/bdist.freebsd-8.3-RELEASE-amd64/egg/setuptools/sandbox.py", line 117, in wrap

OSError: [Errno 13] Permission denied
```

**Comment by monkeython** [comment]
don't know how to fix this. I've no access to a BSD to reproduce this.

**Comment by monkeython** [comment]
This issues should have been caused by wrong dependencies in setup.py. Now should have been fixed.
Thanks.
